require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - final.gemspec
    - Gemfile
    - Rakefile

Lint/AssignmentInCondition:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/EmptyBlock:
  Exclude:
    - spec/*.rb
Lint/MissingSuper:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false 
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RedundantBegin:
  Enabled: false   
Style/SafeNavigation:
  Enabled: false
Style/Semicolon:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
